export { DetailContent } from './detailContent';
export { DetailHeader } from './detailHeader';
export { DetailRecurit } from './detailRecurit';
export { DetailPlatform } from './detailPlatform';
export { DetailSkill } from './detailSkill';
export { DetailReference } from './detailReference';
export { DetailCommentInput } from './detailCommentInput';
export { DetailCommentLog } from './detailCommentLog';
export { DetailRightCard } from './detailRightCard';
